---
- name: Converge
  hosts: all
  vars:
    docker_compose_generator_output_path: '~'
    docker_compose_generator_uid: 1000
    docker_compose_generator_gid: 1000
    containers:
      - name: apache2
        active: true
        image: ubuntu/apache2:2.4-22.04_beta
        ports:
          - 80:80
        environment:
          - TZ=UTC

  roles:
    - role: ../../../ansible-role-docker-compose-generator

  # tasks:
  #   - ansible.builtin.import_tasks: ../../tasks/main.yml
